package io.github.sopheakboth83.dao;

import com.google.inject.Inject;

import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity DCompetition.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2016-02-05T19:32:39.130+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DCompetitionDaoBean 
	extends GeneratedDCompetitionDaoImpl
{

  @Inject
  public DCompetitionDaoBean(Supplier<Object, Object, Object, Object> supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
