package io.github.sopheakboth83.dao;

import com.google.inject.Inject;
import io.github.sopheakboth83.domain.DEvent;
import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity DEvent.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2016-02-07T10:10:04.924+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DEventDaoBean 
	extends GeneratedDEventDaoImpl
{

  @Inject
  public DEventDaoBean(Supplier supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
