package io.github.sopheakboth83.dao;

import com.google.inject.Inject;

import net.sf.mardao.dao.Supplier;

/**
 * Implementation of Business Methods related to entity DHeat.
 * This (empty) class is generated by mardao, but edited by developers.
 * It is not overwritten by the generator once it exists.
 *
 * Generated on 2016-02-08T19:15:05.306+0100.
 * @author mardao DAO generator (net.sf.mardao.plugin.ProcessDomainMojo)
 */
public class DHeatDaoBean 
	extends GeneratedDHeatDaoImpl
{

  @Inject
  public DHeatDaoBean(Supplier supplier) {
    super(supplier);
  }

	// TODO: implement your Business Methods here

}
